spring:
    application:
        name: LibraryService
    datasource:
        url: jdbc:mysql://localhost/available_books_db
        username: root
        password: admin
    jpa:
        hibernate:
            ddl-auto: update

feign:
    hystrix:
        enabled: true
server:
    port: 8081

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
            registerWithEureka: true
            fetchRegistry: true

jwt:
    secret: your-secure-secret-key-that-is-at-least-32-characters