spring:
  application:
    name: BookService

  datasource:
    url: jdbc:mysql://localhost/books_db
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      registerWithEureka: true
      fetchRegistry: true

jwt:
  secret: your-secure-secret-key-that-is-at-least-32-characters